from . import estate_building
from . import estate_unit
from . import rent_contract
from . import inherit_partner
from . import inherit_sale_order
from . import inherit_account_move
from . import rent_prepayment
from . import utility_wizard
from . import utility